custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
spring:
  cloud:
    aws:
      s3:
        bucket-name: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
